<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jugadores de la selección</title>
</head>
<body>
    <h1>Listado de jugadores</h1>

    <?php if (!isset($_SESSION['usuario'])): ?>
        <a href="login">Iniciar sesión</a>
    <?php else: ?>
        <a href="logout">Cerrar sesión</a>
    <?php endif; ?>

    <h2>Lista de jugadores</h2>
    <table border="3">
        <thead>
            <tr>
                <th>Selección</th>
                <th>Nombre</th>
                <?php if ($isAdmin): ?>
                    <th>Acciones</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($jugadores)): ?>
                <tr>
                    <td colspan="8">No hay jugadores cargados</td>
                </tr>
            <?php else: ?>

                <?php foreach ($jugadores as $jugador): ?>
                    <tr>
                        <td><?= $jugador->Seleccion ?></td>
                        <td>
                            <a href="<?= BASE_URL ?>detalle/<?= $jugador->id_jugador ?>">
                                <?= $jugador->nombre ?>
                            </a>
                        </td>
                        <?php if ($isAdmin): ?>
                            <td>
                                <a href="<?= BASE_URL ?>formEdit/<?= $jugador->id_jugador ?>">Editar</a>
                                <a href="<?= BASE_URL ?>delete/<?= $jugador->id_jugador ?>">Eliminar</a>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>

            <?php endif; ?>

        </tbody>
    </table>
    <?php if ($isAdmin): ?>
        <h2>Agregar Nuevo Jugador</h2>
        <?php require __DIR__ . '/JugadorAdd.phtml'; ?>
    <?php endif; ?>
</body>
</html>
