<form method="POST" action="addSeleccion">
    <label for="pais">Nombre de la Seleccion:</label>
    <input id="pais" name="pais" required>

    <label for="dt_seleccion">Director Tecnico:</label>
    <input id="dt_seleccion" name="dt_seleccion" required>

    <label for="cant_mundiales_ganados">Cantidad de mundiales ganados:</label>
    <input id="cant_mundiales_ganados" name="cant_mundiales_ganados" type="number" required>

    <label for="participaciones_totales">Participaciones Totales:</label>
    <input id= "participaciones_totales" name="participaciones_totales" type="number" required>


    <label for="foto_seleccion">URL de la foto:</label>
    <input id="foto_seleccion" name="foto_seleccion" type= "url">

    <button type="submit">Guardar</button>
</form>