<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Album Mundial 2026</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="<?= BASE_URL ?>style/home.css">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <a class="navbar-brand" href="<?= BASE_URL ?>">
            <i class="bi bi-trophy-fill"></i>
            Album virtual - Mundial 2026
        </a>

    <div class="navbar-nav me-auto">
        <a class="nav-link text-white" href="<?= BASE_URL ?>selecciones">
            Selecciones
        </a>

        <a class="nav-link text-white" href="<?= BASE_URL ?>jugadores">
            Jugadores
        </a>
    </div>

        <div class="navbar-nav">

            <?php if(isset($_SESSION['usuario'])): ?>

                <span class="navbar-text me-3">
                    <i class="bi bi-person-circle"></i>
                    Administrador
                </span>

                <a class="nav-link" href="<?= BASE_URL ?>logout">
                    <i class="bi bi-box-arrow-right"></i>
                    Cerrar Sesión
                </a>
            <?php else: ?>

                <a class="nav-link" href="<?= BASE_URL ?>login">
                    Iniciar Sesión
                    <i class="bi bi-box-arrow-in-right ms-2"></i>
                </a>

            <?php endif; ?>
        </div>
    </div>
</nav>
