<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style/home.css">
    <title></title>
</head>
<body>
    <h1>Álbum de figuritas digital- Mundial 2026</h1>
    <div class="pantalla-inicial">
        <div class="izq">
            <img src="https://www.cronista.com/resizer/v2/QOSF3YK2PFENDGJVL2ZALR3LBE.jpg?auth=f9380a4fcc5e5e3a2f7350b12ee8d2a31771b7fbe4b9b6a17220a4de31825237&height=675&width=1200&quality=70&smart=true" alt="Selecciones">
            <button>Ver selecciones</button>
        </div>
        <div class="der">
            <img src="https://a3.espncdn.com/combiner/i?img=%2Fphoto%2F2023%2F0828%2Fr1216817_1294x728_16%2D9.jpg" alt="Jugadores">
            <button>Ver jugadores</button>
        </div>
    </div>
</body>
</html>