<?php require 'layout/header.phtml'; ?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style/home.css">
    <title>Album virtual - Mundial 2026</title>
</head>
<body>
    <h1 class="text-center my-5 text-dark fw-bold">Album virtual - Mundial 2026</h1>

    <div class="pantalla-inicial d-flex justify-content-center align-items-center flex-wrap">
        <div class="izq position-relative m-3">
            <img src="https://www.lanacion.com.ar/resizer/v2/el-sorteo-final-rumbo-al-mundial-de-2026sera-4CB7HCG43VCE7HK2BWKUFLJZ2A.jpg?auth=29007a71800b8e00ccbadd514c004b218a7603d951d437670305310377d04757&width=1200&height=675&quality=70&smart=true" alt="Selecciones" class="img-fluid rounded shadow">
            <a href="<?= BASE_URL ?>selecciones" class="btn btn-primary position-absolute top-50 start-50 translate-middle">Ver selecciones</a>
        </div>
        <div class="der position-relative m-3">
            <img src="https://library.sportingnews.com/styles/crop_style_16_9_desktop_webp/s3/2025-12/Stylized-WC-graphic-with-player-cutouts%20%281%29.jpg.webp?itok=uqLdOADf" alt="Jugadores" class="img-fluid rounded shadow">
            <a href="<?= BASE_URL ?>jugadores" class="btn btn-primary position-absolute top-50 start-50 translate-middle">Ver jugadores</a>
        </div>
    </div>
</body>
</html>
<?php require 'layout/footer.phtml'; ?>