<h1>Detalle del jugador</h1>

<table border="3">
    <tr>
        <th>Nombre</th>
        <td><?= $jugador->nombre ?></td>
    </tr>
    <tr>
        <th>Selección</th>
        <td><?= $jugador->Seleccion ?></td>
    </tr>
    <tr>
        <th>Posición</th>
        <td><?= $jugador->posicion ?></td>
    </tr>
    <tr>
        <th>Número</th>
        <td><?= $jugador->numero ?></td>
    </tr>
    <tr>
        <th>Peso</th>
        <td><?= $jugador->peso ?></td>
    </tr>
    <tr>
        <th>Altura</th>
        <td><?= $jugador->altura ?></td>
    </tr>
    <tr>
        <th>Fecha nacimiento</th>
        <td><?= $jugador->fecha_nacimiento ?></td>
    </tr>
    <tr>
        <th>Foto</th>
        <td>
            <img src="<?= $jugador->foto_jugador ?>" alt="Foto de <?= $jugador->nombre ?>" width="150">
        </td>
    </tr>
</table>

<a href="<?= BASE_URL ?>jugadores">Volver</a>