<?php require 'layout/header.phtml'; ?>

    <div class="container mt-4">
        <h1 class="mb-4 text-center">Lista de Jugadores</h1>

        <table class="table table-striped table-hover table-bordered align-middle">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Posición</th>
                    <th>Número</th>
                    <th>Peso</th>
                    <th>Altura</th>
                    <th>Fecha Nacimiento</th>
                    <th>Foto</th>
                </tr>
            </thead>
            <tbody>

                <?php if (empty($jugadores)): ?>
                    <tr>
                        <td colspan="8" class="text-center">No hay jugadores cargados</td>
                    </tr>
                <?php else: ?>

                    <?php foreach ($jugadores as $jugador): ?>
                        <tr>
                            <td><?= $jugador->nombre ?></td>
                            <td><?= $jugador->posicion ?></td>
                            <td><?= $jugador->numero ?></td>
                            <td><?= $jugador->peso ?></td>
                            <td><?= $jugador->altura ?></td>
                            <td><?= $jugador->fecha_nacimiento ?></td>
                            <td>
                                <img src="<?= $jugador->foto_jugador ?>" width="50"
                                class="img-thumbnail">
                            </td>
                        </tr>
                    <?php endforeach; ?>

                <?php endif; ?>

            </tbody>
        </table>
    </div>
        </body>
        <?php require 'layout/footer.phtml'; ?>
        </html>