<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style/home.css">
    <link rel="stylesheet" href="style/jugador.css">
    <title>Jugadores de la selección</title>
</head>
<body>
    <h1>Listado de jugadores</h1>

    <?php if (!isset($_SESSION['usuario'])): ?>
        <a href="login" class="button">Iniciar sesión</a>
    <?php else: ?>
        <a href="logout" class="button">Cerrar sesión</a>
    <?php endif; ?>

    <table>
        <thead>
            <tr>
                <th>Selección</th>
                <th>Nombre</th>
                <?php if ($isAdmin): ?>
                    <th>Acciones</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($jugadores)): ?>
                <tr>
                    <td colspan="3">No hay jugadores cargados</td>
                </tr>
            <?php else: ?>

                <?php foreach ($jugadores as $jugador): ?>
                    <tr>
                        <td><?= $jugador->Seleccion ?></td>
                        <td>
                            <a class="link_jug" href="<?= BASE_URL ?>detalle/<?= $jugador->id_jugador ?>" >
                                <?= $jugador->nombre ?>
                            </a>
                        </td>
                        <?php if ($isAdmin): ?>
                            <td>
                                <a href="<?= BASE_URL ?>formEdit/<?= $jugador->id_jugador ?>" class="btnEdit">Editar</a>
                                <a href="<?= BASE_URL ?>confirmDelete/<?= $jugador->id_jugador ?>" class="btnDelete">Eliminar</a>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>

            <?php endif; ?>

        </tbody>
        <?php if ($isAdmin): ?>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <a href="<?= BASE_URL ?>formAdd" class="btnAdd">
                            + Agregar Nuevo Jugador
                        </a>
                    </td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
    
</body>
</html>
