<?php require 'layout/header.phtml'; ?>

<body>
<div class="container mt-4">
    <h1 class="mb-4 text-center p-3">Detalle del jugador</h1>

    <table class="table table-striped table-hover table-bordered align-middle">
        <thead class="table-dark">
                <tr class="text-center">
                    <th>Nombre</th>
                    <th>Selección</th>
                    <th>Posición</th>
                    <th>Número</th>
                    <th>Peso</th>
                    <th>Altura</th>
                    <th>Fecha Nacimiento</th>
                    <th>Foto</th>
                </tr>
        </thead>
        <tbody>
            <tr class="text-center">
                <td><?= $jugador->nombre ?></td>
                <td><?= $jugador->Seleccion ?></td>
                <td><?= $jugador->posicion ?></td>
                <td><?= $jugador->numero ?></td>
                <td><?= $jugador->peso ?></td>
                <td><?= $jugador->altura ?></td>
                <td><?= $jugador->fecha_nacimiento ?></td>
                <td>
                    <img src="<?= $jugador->foto_jugador ?>" alt="Foto de <?= $jugador->nombre ?>" width="150">
                </td>
            </tr>
        </tbody>
        
    </table>
    <a href="<?= BASE_URL ?>jugadores" class="btn btn-primary">
        <i class="bi bi-arrow-bar-left"></i>
    Volver
    </a>
</div>
</body>
    <?php require 'layout/footer.phtml'; ?>
    </html>