<?php require 'layout/header.phtml'; ?>
<h2 class="text-center mb-4">Agregar Nuevo Jugador</h2>

<form method="POST" action="add" class="formAdd container mt-5">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre del jugador:</label>
        <input name="nombre" class="form-control">
    </div>
    <div class="mb-3">
        <label for="posicion" class="form-label">Posición:</label>
        <input name="posicion" class="form-control">
    </div>
    <div class="mb-3">
        <label for="numero" class="form-label">Número de camiseta:</label>
        <input name="numero" type="number" class="form-control">
    </div>
    <div class="mb-3">
        <label for="peso" class="form-label">Peso:</label>
        <input name="peso" type="number" class="form-control">
    </div>
    <div class="mb-3">
        <label for="altura" class="form-label">Altura:</label>
        <input name="altura" type="number" class="form-control">
    </div>
    <div class="mb-3">
        <label for="fecha_nacimiento" class="form-label">Fecha de nacimiento:</label>
        <input name="fecha_nacimiento" type="date" class="form-control">
    </div>
    <div class="mb-3">
        <select name="id_seleccion" required class="form-select">
        <option value="">Seleccione una selección</option>
        <?php foreach ($selecciones as $seleccion): ?>
            <option value="<?= $seleccion->id_seleccion ?>">
                <?= $seleccion->pais ?>
            </option>
        <?php endforeach; ?>
        </select>
    </div>
    <div class="mb-4">
        <label for="foto_jugador" class="form-label">URL de la foto:</label>
        <input name="foto_jugador" class="form-control">
    </div>

    <button type="submit" class="btn btn-success w-100">Guardar</button>
</form>
    <a href="<?= BASE_URL ?>jugadores" class="btn btn-primary">
        ← Volver
    </a>
<?php require 'layout/footer.phtml'; ?>