<?php require 'Views/templates/layout/header.phtml'; ?>


<body>
    <h1 class="mb-4 text-center p-3">Lista de jugadores</h1>

    <div  class="container mt-4">
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th class="text-center">Selección</th>
                    <th class="text-center">Nombre</th>
                    <th></th>
                    <?php if ($isAdmin): ?>
                        <th class="text-center">Acciones</th>
                    <?php endif; ?>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($jugadores)): ?>
                    <?php if ($isAdmin): ?>
                        <tr>
                            <td colspan="4">No hay jugadores cargados</td>
                        </tr>
                    <?php else: ?>
                        <tr>
                            <td colspan="3">No hay jugadores cargados</td>
                        </tr>
                    <?php endif; ?>
                <?php else: ?>

                    <?php foreach ($jugadores as $jugador): ?>
                        <tr>
                            <td class="text-center"><?= $jugador->Seleccion ?></td>
                            <td class="text-center"><?= $jugador->nombre ?></td>
                            <td class="text-center"><a href="<?= BASE_URL ?>detalle/<?= $jugador->id_jugador ?>" class="btn btn-primary btn-sm">Ver detalle</td>
                            <?php if ($isAdmin): ?>
                                <td class="text-center">
                                    <a href="<?= BASE_URL ?>formEdit/<?= $jugador->id_jugador ?>" class="btn btn-warning btn-sm">Editar</a>
                                    <a href="<?= BASE_URL ?>confirmDelete/<?= $jugador->id_jugador ?>" class="btn btn-danger btn-sm">Eliminar</a>
                                </td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>

                <?php endif; ?>

            </tbody>
            <?php if ($isAdmin): ?>
                <tfoot>
                    <tr>
                        <td colspan="4" class="text-center">
                            <a href="<?= BASE_URL ?>formAdd" class="btn btn-success">
                                + Agregar Nuevo Jugador
                            </a>
                        </td>
                    </tr>
                </tfoot>
            <?php endif; ?>
        </table>
    </div>
</body>
<?php require 'layout/footer.phtml'; ?>
</html>
