<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
</head>
<body>
    <?php if (!empty($error)): ?>
        <p><?= $error ?></p>
    <?php endif; ?>
    <form action="verificar" method="POST">
        <label for="usuario">Usuario:</label>
        <input type="text" name="usuario" placeholder="Ingrese su nombre de usuario" required>

        <label for="password">Password:</label>
        <input type="password" name ="password" placeholder="Ingrese su contraseña" required>
            
        <button type="submit">Login</button>
    </form>
</body>
</html>