<?php require 'Views/templates/layout/header.phtml'; ?>
<body class="container py-4">
    <?php if (!empty($error)): ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endif; ?>
    <form action="verificar" method="POST" class="mx-auto" style="max-width: 400px;">
        <div class="mb-3">
            <label for="usuario" class="form-label">Usuario:</label>
            <input type="text" name="usuario" class="form-control" placeholder="Ingrese su nombre de usuario" required>
        </div>
        <div class="mb-3">
            <label for="password" "form-label">Password:</label>
            <input type="password" name ="password" class="form-control" placeholder="Ingrese su contraseña" required>
        </div>
        
        <button type="submit" class="btn btn-primary w-100">Login</button>
    </form>
</body>
<?php require 'layout/footer.phtml'; ?>