<?php require 'layout/header.phtml'; ?>
<form method="POST" action="addSeleccion" class="formAddSeleccion container mt-5">

    <h2 class="text-center mb-4">Agregar Nueva Selección</h2>

    <div class="mb-3">
        <label for="pais" class="form-label">Nombre de la Seleccion:</label>
        <input id="pais" name="pais"  class="form-control" required>
    </div>

    <div class="mb-3">
        <label for="dt_seleccion" class="form-label">Director Tecnico:</label>
        <input id="dt_seleccion" name="dt_seleccion" class="form-control" required>
    </div>

    <div class="mb-3">
        <label for="cant_mundiales_ganados" class="form-label">Cantidad de mundiales ganados:</label>
        <input id="cant_mundiales_ganados" name="cant_mundiales_ganados" type="number" class="form-control" required>
    </div>

    <div class="mb-3">
        <label for="participaciones_totales"  class="form-label">Participaciones Totales:</label>
        <input id= "participaciones_totales" name="participaciones_totales" type="number" class="form-control" required>
    </div>

    <div class="mb-4">
        <label for="foto_seleccion" class="form-label">URL de la foto:</label>
        <input id="foto_seleccion" name="foto_seleccion" type= "url" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-success w-100">Guardar</button>
</form>
    <a href="<?= BASE_URL ?>jugadores" class="btn btn-primary ms-3">
        <i class="bi bi-arrow-bar-left"></i>
        Volver
    </a>
<?php require 'layout/footer.phtml'; ?>