<?php require 'layout/header.phtml'; ?>

        <h1 class="mb-4 text-center p-3">Lista de Selecciones</h1>

        <div  class="container mt-4">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>País</th>
                    <th>DT</th>
                    <th>Cantidad de Mundiales Ganados</th>
                    <th>Participaciones Totales</th>
                    <th>Foto</th>
                    <th colspan= "6">Acciones</th>
                
                </tr>
            </thead>
            <tbody>

                <?php if (empty($selecciones)): ?>
                    <tr>
                        <td colspan="4">No hay selecciones cargadas</td>
                    </tr>
                <?php else: ?>

                    <?php foreach ($selecciones as $seleccion): ?>
                        <tr>
                            <td><?= $seleccion->pais ?></td>
                            <td><?= $seleccion->dt_seleccion ?></td>
                            <td><?= $seleccion->cant_mundiales_ganados ?></td>
                            <td><?= $seleccion->participaciones_totales ?></td>
                            <td>
                                <img src="<?= $seleccion->foto_seleccion ?>" alt="Foto de <?= $seleccion->pais ?>" width="100">
                            </td>
                            <td><a href="<?= BASE_URL ?>jugadoresPorSeleccion/<?= $seleccion->id_seleccion ?>" class="btn btn-primary btn-sm">
                            Ver jugadores</td>
                            <?php if ($isAdmin): ?>
                            <td><a href="<?= BASE_URL ?>formEditSeleccion/<?= $seleccion->id_seleccion ?>" class="btn btn-warning btn-sm">Editar</a></td>
                            <td><a href="<?= BASE_URL ?>confirmDeleteSeleccion/<?= $seleccion->id_seleccion ?>" class="btn btn-danger btn-sm">Eliminar</a></td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>

                <?php endif; ?>

            </tbody>
            <?php if ($isAdmin): ?>
            <tfoot>
                <tr>
                    <td colspan="8" class="text-center">
                        <a href="<?= BASE_URL ?>formAddSeleccion" class="btn btn-success">
                            + Agregar Nueva Seleccion
                        </a>
                    </td>
                </tr>
            </tfoot>
        <?php endif; ?>
        </table>
        </div>
        </body>
        <?php require 'layout/footer.phtml'; ?>
        </html>